spring:
  application:
    name: Spring-ai-ollama

  ai:
    ollama:
      base-url: http://localhost:11434

      chat:
        options:
          model: codellama:latest
          temperature: 0.1


server:
  port: 8080


